### ISSUE TITLE
Unhandled error event

### ISSUE THREAD

**Issue by abrownsword** [hobbyquaker/homekit2mqtt#134]
What have I done to cause this?  I don't know where the event.js code is in order to inspect it.  I'm on version 1.1.2 of homekit2mqtt

2018-10-01 16:57:31.455 <debug> mqtt subscribe #
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51888
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at Function.listen (/usr/lib/node_modules/homekit2mqtt/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/usr/lib/node_modules/homekit2mqtt/index.js:478:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)

**Comment by abrownsword** [comment]
EADDRINUSE -- obviously I have another instance still running.
