### ISSUE TITLE
Error: libnode.so.64: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by joearkay** [hobbyquaker/homekit2mqtt#156]
Hi all, I'm having an issue with the latest version of homekit2mqtt. This seemed to run fine on a fresh install of Raspbian, however since installed Node-RED and rebooting I'm having this issue. I'm running v10.16.3 of Node.js

```
homekit2mqtt
/usr/local/lib/node_modules/homekit2mqtt/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: libnode.so.64: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:807:18)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at bindings (/usr/local/lib/node_modules/homekit2mqtt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
```

**Comment by joearkay** [comment]
I fixed this - it seems installing Node-RED afterwards removed some dependencies. Worth noting for others, install Node-RED first and then homekit2mqtt if you want to use the two hand in hand.
