### ISSUE TITLE
Can't start on Ubuntu Server 14.04

### ISSUE THREAD

**Issue by jelimoore** [hobbyquaker/homekit2mqtt#16]
Hello,
I am trying to use this on Ubuntu Server 14.04. The error node gives me is:

2016-10-17 20:54:51.344 <info>  homekit2mqtt 0.4.7 starting
2016-10-17 20:54:51.594 <info>  loading HomeKit to MQTT mapping file /usr/local/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2016-10-17 20:54:51.595 <info>  mqtt trying to connect mqtt://127.0.0.1
2016-10-17 20:54:51.606 <info>  using hap-nodejs version 0.4.11
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>

/usr/local/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/util/eventedhttp.js:62
    let port = this._tcpServer.address().port;
    ^^^
SyntaxError: Unexpected strict mode reserved word
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/HAPServer.js:11:25)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by hobbyquaker** [comment]
I guess your Nodejs doesn't fulfill the prerequisites. You need at least Nodejs 4.3.2

**Comment by jelimoore** [comment]
Using Node v6 from the Nodesource PPA. It now gives me this:

2016-10-18 20:03:22.649 <info>  homekit2mqtt 0.4.7 starting
2016-10-18 20:03:22.908 <info>  loading HomeKit to MQTT mapping file /usr/local/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2016-10-18 20:03:22.910 <info>  mqtt trying to connect mqtt://127.0.0.1
2016-10-18 20:03:22.929 <info>  using hap-nodejs version 0.4.11
/usr/local/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:35
    throw ex;
    ^

Error: Module did not self-register.
    at Error (native)
    at Object.Module._extensions..node (module.js:597:18)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/node_modules/mdns/lib/dns_sd.js:24:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)

**Comment by hobbyquaker** [comment]
have you reinstalled after updating your Nodejs? Did you meet all prerequisites?
```
sudo apt-get install libavahi-compat-libdnssd-dev
sudo rm -r /usr/local/lib/node_modules/homekit2mqtt 
sudo npm install -g homekit2mqtt
```

**Comment by jelimoore** [comment]
Ok, I'm officially dumb. Forgot to remove the package after reinstalling Node... Sorry.
