### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by sorriso93** [hobbyquaker/homekit2mqtt#160]
Hello
I have problem installing it... any suggestion?
Many thanks

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.81-v7l+
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ed25519-hap@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ed25519-hap@0.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-04T11_26_53_304Z-debug.log

**Comment by sorriso93** [comment]
last portion of the log...

6658 info lifecycle curve25519-n@1.5.0~install: curve25519-n@1.5.0
6659 verbose lifecycle curve25519-n@1.5.0~install: unsafe-perm in lifecycle true
6660 verbose lifecycle curve25519-n@1.5.0~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/n$
6661 verbose lifecycle curve25519-n@1.5.0~install: CWD: /usr/local/lib/node_modules/homekit2mqtt/node_modules/curve25519-n
6662 silly lifecycle curve25519-n@1.5.0~install: Args: [ '-c', 'node-gyp rebuild' ]
6663 silly lifecycle curve25519-n@1.5.0~install: Returned: code: 0  signal: null
6664 silly install ed25519-hap@0.0.5
6665 info lifecycle ed25519-hap@0.0.5~install: ed25519-hap@0.0.5
6666 verbose lifecycle ed25519-hap@0.0.5~install: unsafe-perm in lifecycle true
6667 verbose lifecycle ed25519-hap@0.0.5~install: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/local/lib/no$
6668 verbose lifecycle ed25519-hap@0.0.5~install: CWD: /usr/local/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap
6669 silly lifecycle ed25519-hap@0.0.5~install: Args: [ '-c', 'node-gyp rebuild' ]
6670 silly lifecycle ed25519-hap@0.0.5~install: Returned: code: 1  signal: null
6671 info lifecycle ed25519-hap@0.0.5~install: Failed to exec install script
6672 timing action:install Completed in 42114ms
6673 verbose unlock done using /root/.npm/_locks/staging-3a08f0df5026584d.lock for /usr/local/lib/node_modules/.staging
6674 timing stage:rollbackFailedOptional Completed in 3043ms
6675 timing stage:runTopLevelLifecycles Completed in 107090ms
6676 verbose stack Error: ed25519-hap@0.0.5 install: `node-gyp rebuild`
6676 verbose stack Exit status 1
6676 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
6676 verbose stack     at EventEmitter.emit (events.js:210:5)
6676 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
6676 verbose stack     at ChildProcess.emit (events.js:210:5)
6676 verbose stack     at maybeClose (internal/child_process.js:1021:16)
6676 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
6677 verbose pkgid ed25519-hap@0.0.5
6678 verbose cwd /root
