### ISSUE TITLE
homekit2mqtt Installation

### ISSUE THREAD

**Issue by Christian2306** [hobbyquaker/homekit2mqtt#162]
Hi all,

I'm trying to install homekit2mqtt but with no success. I get the following error message:

```
homekit2mqtt -u
/usr/local/lib/node_modules/homekit2mqtt/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: The module '/usr/local/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap/build/Release/ed25519.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 79. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1194:18)
    at Module.load (internal/modules/cjs/loader.js:993:32)
    at Function.Module._load (internal/modules/cjs/loader.js:892:14)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at bindings (/usr/local/lib/node_modules/homekit2mqtt/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/usr/local/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1144:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1164:10)
    at Module.load (internal/modules/cjs/loader.js:993:32)
```

I already tried the command _npm rebuild_ and _npm install_, but that didn't solve the problem. I've tried the newest version of node.js, the result is the same.

Can anyone give an advice how to get the problem solved? What is the correct version of _NODE_MODULE_VERSION 79_?

Thanks in advance for your help! 

Christian

**Comment by oyagci** [comment]
Try running with node 8.
I use `nvm` to handle have different versions of node on my computer.

**Comment by iCarl** [comment]
I have the same issue, tried installing it with node v8, but I couldn't get it to work.
Edit: not the same issue
