### ISSUE TITLE
Error while trying to install

### ISSUE THREAD

**Issue by iCarl** [hobbyquaker/homekit2mqtt#164]
Error message when installing:

Nodejs version 12.14.1
npm version 6.13.4

```
In file included from /root/.cache/node-gyp/12.14.1/include/node/node.h:63,
                 from ../src/ed25519.cc:1:
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
/root/.cache/node-gyp/12.14.1/include/node/node_object_wrap.h:84:78:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
                reinterpret_cast<Callback>(callback), type);
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/root/.cache/node-gyp/12.14.1/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
../../nan/nan_object_wrap.h:65:61:   required from here
/root/.cache/node-gyp/12.14.1/include/node/v8.h:10004:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
make: *** [ed25519.target.mk:149: Release/obj.target/ed25519/src/ed25519.o] Error 1
make: Leaving directory '/usr/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.19.75-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/npm-lifecycle/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/homekit2mqtt/node_modules/ed25519-hap
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ed25519-hap@0.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ed25519-hap@0.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-01-28T07_12_45_807Z-debug.log
```

What could be the cause of this?
I've tried to install using a different version of NodeJS, reinstalling gyp, clearing npm cache and more

**Comment by 0X-XYZ** [comment]
I too am debugging this issue. It looks like the creator doesn't frequent this page any more.

I have noticed this issue appears more for me when using the later versions on Node.js and homebridge on the same machine.

Changing my node version seems to brick my other programs too.

**Comment by abrownsword** [comment]
Any updates on this?  I'm trying to build with the latest nodejs LTS release.

**Comment by chrispi68** [comment]
I am currently migrating to mqttthing/homebridge beacuse homekit2mqtt is not maintained any more. mqttthing has the same functionality and frequent updates.

https://github.com/arachnetech/homebridge-mqttthing#readme

**Comment by abrownsword** [comment]
Yeah, this project hasn't been looking promising for nearly 2 years now, sadly.  Thanks for the pointer to an alternative!  Guess I have some dev work to do in order to migrate.
