### ISSUE TITLE
MQTT disconnecting when trying to publish.

### ISSUE THREAD

**Issue by oriolism** [hobbyquaker/homekit2mqtt#19]
I trying to open and close the garage door from homekit app but it looks like the MQTT server is not receiving the message. 

homekit2mqtt.json  configuration:
{
        "GarageDoorOpener": {
                "service": "GarageDoorOpener",
                "name": "Garage Door",
                "topic": {
                "setDoor": "GarageDoor/Set",
                "statusDoor": "GarageDoor/Status"
                },
                "payload": {
                "doorOpen": "OpenGarageDoor",
                "doorClosed": "CloseGarageDoor"
                },
                "manufacturer": "Generic",
                "model": "Generic"
        }
}

****Logs on server running homekit2mqtt and homebridge: ****

pi@raspberrypi:~ $ sudo homekit2mqtt -v debug
2016-11-06 12:19:50.855 <info>  homekit2mqtt 0.5.2 starting
2016-11-06 12:19:51.974 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2016-11-06 12:19:51.981 <info>  mqtt trying to connect mqtt://192.168.0.10
2016-11-06 12:19:52.069 <info>  using hap-nodejs version 0.4.13
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2016-11-06 12:19:52.742 <debug> addBridgedAccessory GarageDoorOpener Garage Door
2016-11-06 12:19:52.766 <debug> mqtt subscribe GarageDoor/Status
2016-11-06 12:19:52.785 <info>  hap created 1 Accessories
2016-11-06 12:19:52.791 <info>  hap publishing bridge "MQTT Bridge" username=AC:A2:AD:A3:AE:A6 port=51832 pincode=031-45-154
2016-11-06 12:19:52.928 <info>  hap Bridge listening on port 51832
2016-11-06 12:19:52.981 <info>  mqtt connected mqtt://192.168.0.10
2016-11-06 12:20:35.377 <debug> < hap get Garage Door CurrentDoorState
2016-11-06 12:20:35.378 <debug> > hap re_get Garage Door CurrentDoorState.OPEN
2016-11-06 12:20:35.382 <debug> < hap get Garage Door ObstructionDetected
2016-11-06 12:20:35.383 <debug> > hap re_get Garage Door ObstructionDetected true
2016-11-06 12:20:35.939 <debug> < hap set Garage Door TargetDoorState 1
2016-11-06 12:20:35.939 <debug> > mqtt publish GarageDoor/Set CloseGarageDoor
2016-11-06 12:20:35.949 <info>  mqtt closed mqtt://192.168.0.10
2016-11-06 12:20:37.008 <info>  mqtt connected mqtt://192.168.0.10
2016-11-06 12:20:47.944 <debug> < hap set Garage Door TargetDoorState 0
2016-11-06 12:20:47.945 <debug> > mqtt publish GarageDoor/Set OpenGarageDoor
2016-11-06 12:20:47.947 <info>  mqtt closed mqtt://192.168.0.10
2016-11-06 12:20:48.960 <info>  mqtt connected mqtt://192.168.0.10

**** Logs on MQTT server: ****

1478452943: New connection from 192.168.0.19 on port 1883.
1478452943: New client connected from 192.168.0.19 as mqttjs_c4826491 (c1, k60).
1478452943: Sending CONNACK to mqttjs_c4826491 (0, 0)
1478452943: Received SUBSCRIBE from mqttjs_c4826491
1478452943: GarageDoor/Status (QoS 0)
1478452943: mqttjs_c4826491 0 GarageDoor/Status
1478452943: Sending SUBACK to mqttjs_c4826491
1478452943: Received PUBLISH from mqttjs_c4826491 (d0, q0, r1, m0, 'homekit/connected', ... (1 bytes))
1478452987: New connection from 192.168.0.19 on port 1883.
1478452987: Client mqttjs_c4826491 already connected, closing old connection.
1478452987: Client mqttjs_c4826491 disconnected.
1478452987: New client connected from 192.168.0.19 as mqttjs_c4826491 (c1, k60).
1478452987: Sending CONNACK to mqttjs_c4826491 (0, 0)
1478452987: Received SUBSCRIBE from mqttjs_c4826491
1478452987: GarageDoor/Status (QoS 0)
1478452987: mqttjs_c4826491 0 GarageDoor/Status
1478452987: Sending SUBACK to mqttjs_c4826491
1478452987: Received PUBLISH from mqttjs_c4826491 (d0, q0, r1, m0, 'homekit/connected', ... (1 bytes))
1478452999: New connection from 192.168.0.19 on port 1883.
1478452999: Client mqttjs_c4826491 already connected, closing old connection.
1478452999: Client mqttjs_c4826491 disconnected.
1478452999: New client connected from 192.168.0.19 as mqttjs_c4826491 (c1, k60).
1478452999: Sending CONNACK to mqttjs_c4826491 (0, 0)
1478452999: Received SUBSCRIBE from mqttjs_c4826491
1478452999: GarageDoor/Status (QoS 0)
1478452999: mqttjs_c4826491 0 GarageDoor/Status
1478452999: Sending SUBACK to mqttjs_c4826491
1478452999: Received PUBLISH from mqttjs_c4826491 (d0, q0, r1, m0, 'homekit/connected', ... (1 bytes))

**Comment by hobbyquaker** [comment]
It seams to disconnect right after publishing on the `homekit/connected` topic. I have no clue why... Which Broker in which version do you use?

**Comment by hobbyquaker** [comment]
I just published 0.5.3, this adds more logging of the mqtt connection and handles error events on publishing. Could you test with this version again to see if we find something useful in the logs?

**Comment by oriolism** [comment]
Getting this after the upgrade. 

pi@raspberrypi:~ $ sudo homekit2mqtt -v debug
/usr/lib/node_modules/homekit2mqtt/index.js:102
        iff (err) log.error('mqtt publish error ' + err);
                  ^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

**Comment by oriolism** [comment]
Ok, that error is a typo on the index.js file. 

Im running Mosquito on the same Raspberry Pi 2 that homebridge and homekit2mqtt are running. I tested with another MQTT server on another linux machine but Im getting the same error. For troubleshooting purposes I add a switch to the homekit2mqtt.json file and i can see the messages on the mqtt server. So it appears to be only on the Garage Door. 

pi@raspberrypi:~ $ sudo homekit2mqtt -v debug
2016-11-06 17:41:39.083 <info>  homekit2mqtt 0.5.5 starting
2016-11-06 17:41:40.235 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2016-11-06 17:41:40.242 <info>  mqtt trying to connect mqtt://192.168.0.19
2016-11-06 17:41:40.328 <info>  using hap-nodejs version 0.4.13
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2016-11-06 17:41:41.018 <debug> addBridgedAccessory GarageDoorOpener Garage Door
2016-11-06 17:41:41.040 <debug> mqtt subscribe GarageDoor/Status
2016-11-06 17:41:41.059 <debug> addBridgedAccessory Switch Coffee Machine
2016-11-06 17:41:41.067 <debug> mqtt subscribe Switch/status
2016-11-06 17:41:41.071 <info>  hap created 2 Accessories
2016-11-06 17:41:41.073 <info>  hap publishing bridge "MQTT Bridge" username=AC:A2:AD:A3:AE:A6 port=51832 pincode=031-45-154
2016-11-06 17:41:41.210 <info>  hap Bridge listening on port 51832
2016-11-06 17:41:41.261 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:41:42.743 <debug> < hap get Garage Door ObstructionDetected
2016-11-06 17:41:42.744 <debug> > hap re_get Garage Door ObstructionDetected true
2016-11-06 17:41:42.755 <debug> < hap get Garage Door CurrentDoorState
2016-11-06 17:41:42.757 <debug> > hap re_get Garage Door CurrentDoorState.OPEN
2016-11-06 17:41:50.261 <debug> < hap set Garage Door TargetDoorState 1
2016-11-06 17:41:50.263 <debug> > mqtt publish GarageDoor/Set CloseGarageDoor
2016-11-06 17:41:50.274 <info>  mqtt offline
2016-11-06 17:41:50.276 <info>  mqtt closed mqtt://192.168.0.19
2016-11-06 17:41:51.277 <info>  mqtt reconnect
2016-11-06 17:41:51.308 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:41:55.566 <debug> < hap set Garage Door TargetDoorState 0
2016-11-06 17:41:55.568 <debug> > mqtt publish GarageDoor/Set OpenGarageDoor
2016-11-06 17:41:55.571 <info>  mqtt offline
2016-11-06 17:41:55.572 <info>  mqtt closed mqtt://192.168.0.19
2016-11-06 17:41:56.573 <info>  mqtt reconnect
2016-11-06 17:41:56.596 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:42:00.637 <debug> < hap set Garage Door TargetDoorState 1
2016-11-06 17:42:00.639 <debug> > mqtt publish GarageDoor/Set CloseGarageDoor
2016-11-06 17:42:00.642 <info>  mqtt offline
2016-11-06 17:42:00.643 <info>  mqtt closed mqtt://192.168.0.19
2016-11-06 17:42:01.644 <info>  mqtt reconnect
2016-11-06 17:42:01.654 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:42:03.370 <debug> < hap set Garage Door TargetDoorState 0
2016-11-06 17:42:03.372 <debug> > mqtt publish GarageDoor/Set OpenGarageDoor
2016-11-06 17:42:03.375 <info>  mqtt offline
2016-11-06 17:42:03.376 <info>  mqtt closed mqtt://192.168.0.19
2016-11-06 17:42:04.377 <info>  mqtt reconnect
2016-11-06 17:42:04.386 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:42:18.420 <debug> < hap set Garage Door TargetDoorState 1
2016-11-06 17:42:18.421 <debug> > mqtt publish GarageDoor/Set CloseGarageDoor
2016-11-06 17:42:18.423 <info>  mqtt offline
2016-11-06 17:42:18.424 <info>  mqtt closed mqtt://192.168.0.19
2016-11-06 17:42:19.425 <info>  mqtt reconnect
2016-11-06 17:42:19.433 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:42:20.834 <debug> < hap set Garage Door TargetDoorState 0
2016-11-06 17:42:20.835 <debug> > mqtt publish GarageDoor/Set OpenGarageDoor
2016-11-06 17:42:20.836 <info>  mqtt offline
2016-11-06 17:42:20.836 <info>  mqtt closed mqtt://192.168.0.19
2016-11-06 17:42:21.837 <info>  mqtt reconnect
2016-11-06 17:42:21.845 <info>  mqtt connected mqtt://192.168.0.19
2016-11-06 17:42:26.056 <debug> < hap get Coffee Machine On
2016-11-06 17:42:26.057 <debug> > hap re_get Coffee Machine On false
2016-11-06 17:42:28.964 <debug> < hap set Coffee Machine On 1
2016-11-06 17:42:28.965 <debug> > mqtt Switch/set 1
2016-11-06 17:42:31.680 <debug> < hap set Coffee Machine On 0
2016-11-06 17:42:31.681 <debug> > mqtt Switch/set 0
2016-11-06 17:42:34.048 <debug> < hap set Coffee Machine On 1
2016-11-06 17:42:34.050 <debug> > mqtt Switch/set 1

**Comment by oriolism** [comment]
I think i found the problem. Change settings.topic.setLock to settings.topic.setDoor. 

 var garage = newAccessory(settings);
        garage.addService(Service.GarageDoorOpener, settings.name)
            .getCharacteristic(Characteristic.TargetDoorState)
            .on('set', function (value, callback) {
                log.debug('< hap set', settings.name, 'TargetDoorState', value);
                if (value == Characteristic.TargetDoorState.OPEN) {
                    log.debug('> mqtt publish', settings.topic.setDoor, settings.payload.doorOpen);
                    mqttPub(settings.topic.setLock, settings.payload.doorOpen);

                    callback();
                } else if (value == Characteristic.TargetDoorState.CLOSED) {
                    log.debug('> mqtt publish', settings.topic.setDoor, settings.payload.doorClosed);
                    mqttPub(settings.topic.setLock, settings.payload.doorClosed);

**Comment by hobbyquaker** [comment]
Thx for you help! One should not publish untested software ;) 
In 0.5.7 everything should be fine now.

**Comment by oriolism** [comment]
No, thanks to you for your time! One last question. To update the status of the Garage Door what payload is expected on homekit2mqtt side?

**Comment by hobbyquaker** [comment]
you can either send plain strings (these are type guessed, see the `mqtt.on('message')` handler) or a JSON object containing a `val` attribute (https://github.com/mqtt-smarthome/mqtt-smarthome/blob/master/Architecture.md). 
So you can for example configure `"payload": { "doorOpen": 1, "doorClosed": 0}`and just use the strings `"0"`and `"1"` in your MQTT publish, they get casted to numbers automatically if you're not sending a JSON object.

**Comment by oriolism** [comment]
There's something weird with the door status. I can see the notification on my iPhone if the door is open or closed but when the door is closed the status on the homekit app stays on "closing". Any ideas of how to fix this?

**Comment by hobbyquaker** [comment]
I guess that depends on setDoor as well as on statusDoor. If statusDoor is "open" but setDoor is "doorClosed" it will show "closing" - and as soon as on statusDoor topic a "doorClosed" is published it will show "closed". Just try to publish your doorClosed payload on the statusDoor topic to see if this is the case.

**Comment by hobbyquaker** [comment]
I think I misunderstood something here. Hopefully this issue is fixed by https://github.com/hobbyquaker/homekit2mqtt/commit/53d5645bcf12dd5ac6c1ff7ac9a3fcba434a2a7f (npm version 0.6.1)

**Comment by oriolism** [comment]
Sorry for the late response. Right know the door updates from Close to Open and from Open to Close but if i close the Homekit app and check the status again, it will stay "Closing" state if the door is closed.

**Comment by hobbyquaker** [comment]
can you try is a publish of the doorClosed payload on the statusDoor and/or setDoor topic changes the display to closed then?

**Comment by oriolism** [comment]
Yes it does fix the status on the app while the app is open. But once is closed and open again the status returns to the "Closing" state. The problem seems to be on the query that the app does every time it opens. Theres any way to remove the opening and closing state and  just use the Open a Closed state?

**Comment by oriolism** [comment]
Found the problem. 

Change this:

            garage.getService(Service.GarageDoorOpener)
                .getCharacteristic(Characteristic.CurrentDoorState)
                .on('get', function(callback) {
                    log.debug('< hap get', settings.name, 'CurrentDoorState');

                    if (mqttStatus[settings.topic.statusDoor] === settings.payload.doorClosed) {
                        log.debug('> hap re_get', settings.name, 'CurrentDoorState.CLOSED');
                        callback(null, Characteristic.CurrentDoorState.SECURED);
                    } else {
                        log.debug('> hap re_get', settings.name, 'CurrentDoorState.OPEN');
                        callback(null, Characteristic.CurrentDoorState.UNSECURED);
                    }
                });
        }

To this:

     garage.getService(Service.GarageDoorOpener)
                .getCharacteristic(Characteristic.CurrentDoorState)
                .on('get', function(callback) {
                    log.debug('< hap get', settings.name, 'CurrentDoorState');

                    if (mqttStatus[settings.topic.statusDoor] === settings.payload.doorClosed) {
                        log.debug('> hap re_get', settings.name, 'CurrentDoorState.CLOSED');
                        callback(null, Characteristic.CurrentDoorState.CLOSED);
                    } else {
                        log.debug('> hap re_get', settings.name, 'CurrentDoorState.OPEN');
                        callback(null, Characteristic.CurrentDoorState.OPEN);
                    }
                });
        }

**Comment by hobbyquaker** [comment]
cool, thx for the fix!
