### ISSUE TITLE
cannot start homekit2mqtt

### ISSUE THREAD

**Issue by ciapamusche** [hobbyquaker/homekit2mqtt#22]
This is my homekit2mqrr.json
```
"Lightbulb1":{
    "service":  "Lightbulb",
    "name":     "Luce studio",
    "topic": {
      "setOn":          "/Bridge01/mcpgpio/9",
      "statusOn":       "/Bridge01/state/stud"
             },

     "payload":{
      "onTrue":0,
      "onFalse":1
             }

 }

```
```
2016-12-09 01:11:42.399 <info>  homekit2mqtt 0.6.5 starting
2016-12-09 01:11:43.002 <info>  mqtt trying to connect mqtt://127.0.0.1
2016-12-09 01:11:43.058 <info>  using hap-nodejs version 0.4.17
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
2016-12-09 01:11:43.356 <info>  using directory /usr/local/lib/node_modules/homekit2mqtt/node_modules/ for persistent storage
2016-12-09 01:11:43.381 <info>  loading HomeKit to MQTT mapping file /usr/local/lib/node_modules/homekit2mqtt/homekit2mqtt.json
module.js:433
    throw err;
    ^

SyntaxError: /usr/local/lib/node_modules/homekit2mqtt/homekit2mqtt.json: Unexpected token :
    at Object.parse (native)
    at Object.Module._extensions..json (module.js:430:27)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> 

(/home/udamianu/.nvm/versions/node/v5.7.0/lib/node_modules/homekit2mqtt/index.js:173:15)

    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

```

only an object to try. from the example..

can you help me?

**Comment by ciapamusche** [comment]
Solved by uninstall node.js and reinstall by apt-get with -g as superuser.
But i can execute it only from my home directory..

How to execute from everywhere? and how to start homekit2mqtt on Boot?

**Comment by hobbyquaker** [comment]
a `sudo npm install -g homekit2mqtt` should install a symlink `/usr/local/bin/homekit2mqtt` and (if /usr/local/bin is in PATH) you should be able to call it from everywhere. I would suggest to check if `/usr/local/bin/homekit2mqtt` exists. If not something went wrong on installation.

For starting homekit2mqtt on boot I suggest to use https://github.com/Unitech/pm2

**Comment by hobbyquaker** [comment]
feel free to reopen if you want further assistance
