### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by zohairshafi** [hobbyquaker/homekit2mqtt#26]
Hello, I get the following error when I try to run homekit2mqtt. I cant make a lot of sense of it. Please help. 

2017-05-22 13:13:23.383 <info>  homekit2mqtt 0.6.5 starting
2017-05-22 13:13:23.946 <info>  mqtt trying to connect mqtt://127.0.0.1
2017-05-22 13:13:23.999 <info>  using hap-nodejs version 0.4.17
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
2017-05-22 13:13:24.505 <info>  loading HomeKit to MQTT mapping file /usr/local/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2017-05-22 13:13:24.511 <debug> loading accessories/WindowCovering.js
/usr/local/lib/node_modules/homekit2mqtt/accessories/WindowCovering.js:3
    var {mqttPub, mqttSub, mqttStatus, log, newAccessory, Service, Characteristic} = iface;
        ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:387:25)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at loadAccessory (/usr/local/lib/node_modules/homekit2mqtt/index.js:168:28)
    at /usr/local/lib/node_modules/homekit2mqtt/index.js:179:9
    at Array.forEach (native)

**Comment by hobbyquaker** [comment]
Seems to be an outdated Node.js version. For homekit2mqtt you need Node.js >= 6.0.0.
