### ISSUE TITLE
Does mosquitto need to install before below command?

### ISSUE THREAD

**Issue by shinyuan** [hobbyquaker/homekit2mqtt#30]
Hi awesome maker (Sebastian Raff),

Does mosquitto need to install before below command?
sudo apt-get install libavahi-compat-libdnssd-dev
sudo npm install -g homekit2mqtt --unsafe-perm
homekit2mqtt -v debug

Before `sudo npm install -g homekit2mqtt --unsafe-perm`
I did
```
sudo apt-get install libmosquitto-dev
sudo apt-get install mosquitto mosquitto-clients
sudo vi /etc/mosquitto/mosquitto.conf
```

```
pid_file /var/run/mosquitto.pid
persistence true
persistence_location /var/lib/mosquitto/
log_dest file /var/log/mosquitto/mosquitto.log
include_dir /etc/mosquitto/conf.d
allow_anonymous false
password_file /etc/mosquitto/pwfile
listener 1883
```

```
root@raspberrypi:/home/pi# sudo mosquitto_passwd -c /etc/mosquitto/pwfile pi
Password: password
Reenter password: password

sudo reboot
```

and

```
mosquitto_sub -d -u pi -P password -t "Nodemcu/Control_R_LED"
mosquitto_pub -d -u pi -P password -t "Nodemcu/Control_R_LED" -m "OFF"
```
is work

But

```
root@raspberrypi:/usr/lib/node_modules/homekit2mqtt# homekit2mqtt -v debug -m /usr/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json -u "tcp://127.0.0.1:1883"
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2017-06-22 07:42:06.935 <info>  homekit2mqtt 0.6.9 starting
2017-06-22 07:42:06.955 <info>  mqtt trying to connect tcp://127.0.0.1:**1883**
2017-06-22 07:42:07.436 <info>  using hap-nodejs version 0.4.25
2017-06-22 07:42:07.485 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json
2017-06-22 07:42:07.494 <debug> loading accessories/Thermostat.js
2017-06-22 07:42:07.504 <debug> addBridgedAccessory Thermostat Thermostat1
2017-06-22 07:42:07.539 <debug> mqtt subscribe Thermostat1/status/CurrentTemperature
2017-06-22 07:42:07.548 <debug> mqtt subscribe Thermostat1/status/TargetTemperature
2017-06-22 07:42:07.551 <debug> mqtt subscribe Thermostat1/status/CurrentHumidity
2017-06-22 07:42:07.564 <debug> loading accessories/WindowCovering.js
2017-06-22 07:42:07.570 <debug> addBridgedAccessory WindowCovering Blind
2017-06-22 07:42:07.588 <debug> mqtt subscribe WindowCovering1/status/TargetPosition
2017-06-22 07:42:07.593 <debug> mqtt subscribe WindowCovering1/status/CurrentPosition
2017-06-22 07:42:07.594 <debug> mqtt subscribe WindowCovering1/status/PositionStatus
2017-06-22 07:42:07.599 <debug> loading accessories/Lightbulb.js
2017-06-22 07:42:07.607 <debug> addBridgedAccessory Lightbulb Licht Garten
2017-06-22 07:42:07.619 <debug> mqtt subscribe Lightbulb1/status
2017-06-22 07:42:07.623 <debug> addBridgedAccessory Lightbulb Lightbulb2
2017-06-22 07:42:07.629 <debug> mqtt subscribe Lightbulb2/status
2017-06-22 07:42:07.631 <debug> mqtt subscribe Lightbulb2/status/Brightness
2017-06-22 07:42:07.633 <debug> addBridgedAccessory Lightbulb Lightbulb3
2017-06-22 07:42:07.635 <debug> mqtt subscribe Lightbulb3/status
2017-06-22 07:42:07.636 <debug> mqtt subscribe Lightbulb3/status/Brightness
2017-06-22 07:42:07.638 <debug> mqtt subscribe Lightbulb3/status/Hue
2017-06-22 07:42:07.639 <debug> mqtt subscribe Lightbulb3/status/Saturation
2017-06-22 07:42:07.641 <debug> loading accessories/Switch.js
2017-06-22 07:42:07.647 <debug> addBridgedAccessory Switch Steckdose Fernseher
2017-06-22 07:42:07.655 <debug> mqtt subscribe Switch/status
2017-06-22 07:42:07.657 <debug> loading accessories/MotionSensor.js
2017-06-22 07:42:07.664 <debug> addBridgedAccessory MotionSensor MotionSensor
2017-06-22 07:42:07.675 <debug> mqtt subscribe MotionSensor/status
2017-06-22 07:42:07.678 <debug> loading accessories/ContactSensor.js
2017-06-22 07:42:07.684 <debug> addBridgedAccessory ContactSensor ContactSensor
2017-06-22 07:42:07.695 <debug> mqtt subscribe ContactSensor/status
2017-06-22 07:42:07.698 <debug> mqtt subscribe ContactSensor/status/LowBattery
2017-06-22 07:42:07.700 <debug> loading accessories/LockMechanism.js
2017-06-22 07:42:07.708 <debug> addBridgedAccessory LockMechanism LockMechanism
2017-06-22 07:42:07.717 <debug> mqtt subscribe LockMechanism/status
2017-06-22 07:42:07.720 <debug> loading accessories/TemperatureSensor.js
2017-06-22 07:42:07.727 <debug> addBridgedAccessory TemperatureSensor TemperatureSensor
2017-06-22 07:42:07.732 <debug> mqtt subscribe TemperatureSensor/Temperature
2017-06-22 07:42:07.737 <debug> loading accessories/LightSensor.js
2017-06-22 07:42:07.742 <debug> addBridgedAccessory LightSensor LightSensor
2017-06-22 07:42:07.746 <debug> mqtt subscribe LightSensor/Brightness
2017-06-22 07:42:07.753 <info>  hap created 11 Accessories
2017-06-22 07:42:07.755 <info>  hap publishing bridge "MQTT Bridge" username=CC:22:3D:E3:CE:F6 port=1883 pincode=031-45-154
events.js:163
      throw er; // Unhandled 'error' event
      ^

**Error: listen EADDRINUSE :::1883**
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at Server.setupListenHandle [as _listen2] (net.js:1259:14)
    at listenInCluster (net.js:1307:12)
    at Server.listen (net.js:1406:7)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homekit2mqtt/node_modules/hap-nodejs/lib/Accessory.js:509:16)
    at Object.<anonymous> (/usr/lib/node_modules/homekit2mqtt/index.js:195:8)
    at Module._compile (module.js:571:32)
root@raspberrypi:/usr/lib/node_modules/homekit2mqtt#
```
Thanks.

**Comment by hobbyquaker** [comment]
That is strange. Obviously homekit2mqtt tries to bind on port 1883 - The port mosquitto has already taken (what is correct). I don't understand why. homekit2mqtt should use the port `51826` by default. You could try again to start homekit2mqtt with supplying the port explicitly (option `--port 51826`).

**Comment by hobbyquaker** [comment]
Another thing I just realized: If you configure your mosquitto with `allow_anonymous false` you also have to supply the credentials when starting homekit2mqtt. Your start command should then look like this:
`homekit2mqtt -u tcp://pi:password@127.0.0.1 -m /usr/lib/node_modules/homekit2mqtt/example-homekit2mqtt.json -v debug --port 51826`

**Comment by shinyuan** [comment]
I will try after 11 hours while I at home.
Does you run mosquitto (port 1883) and homekit2mqtt (port 1883)
  at the same Raspberry Pi?!
Thanks.

**Comment by hobbyquaker** [comment]
Homekit2mqtt should _not_ listen on port 1883. This is the standard mqtt port mosquitto is listening on. On one host only one application can listen on a specific port. Homekit2mqtt itself should listen on port 51826. I fear you're mistaking _listening_ ports and _outgoing_ connections. Just try to start homekit2mqtt with the commandline I posted above and paste the log if it does not work.

**Comment by shinyuan** [comment]
first run at terminal #1:
sudo vi homekit2mqtt.json

{
  "Lightbulb1": {
    "service": "Lightbulb",
    "name": "Red LED",
    "topic": {
      "setOn": "Nodemcu/Control_R_LED/set",
      "statusOn": "Nodemcu/Control_R_LED/status"
    },
    "payload": {
      "onTrue": "ON",
      "onFalse": "OFF"
    },
    "manufacturer": "Generic",
    "model": "Lightbulb"
  },

  "Lightbulb2": {
    "service": "Lightbulb",
    "name": "Green LED",
    "topic": {
      "setOn": "Nodemcu/Control_G_LED/set",
      "statusOn": "Nodemcu/Control_G_LED/status"
    },
    "payload": {
      "onTrue": "ON",
      "onFalse": "OFF"
    },
    "manufacturer": "Generic",
    "model": "Lightbulb"
  },

  "Lightbulb3": {
    "service": "Lightbulb",
    "name": "Yellow LED",
    "topic": {
      "setOn": "Nodemcu/Control_Y_LED/set",
      "statusOn": "Nodemcu/Control_Y_LED/status"
    },
    "payload": {
      "onTrue": "ON",
      "onFalse": "OFF"
    },
    "manufacturer": "Generic",
    "model": "Lightbulb"
  }
}


second run at terminal #1:
homekit2mqtt -u tcp://pi:password@127.0.0.1 \
    -m /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json \
    -v debug \
    --port 51826

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2017-06-24 00:20:39.922 <info>  homekit2mqtt 0.6.9 starting
2017-06-24 00:20:39.940 <info>  mqtt trying to connect tcp://pi:password@127.0.0.1
2017-06-24 00:20:40.448 <info>  using hap-nodejs version 0.4.25
2017-06-24 00:20:40.503 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json
2017-06-24 00:20:40.514 <debug> loading accessories/Lightbulb.js
2017-06-24 00:20:40.531 <debug> addBridgedAccessory Lightbulb Red LED
2017-06-24 00:20:40.555 <debug> mqtt subscribe Nodemcu/Control_R_LED/status
2017-06-24 00:20:40.572 <debug> addBridgedAccessory Lightbulb Green LED
2017-06-24 00:20:40.580 <debug> mqtt subscribe Nodemcu/Control_G_LED/status
2017-06-24 00:20:40.586 <debug> addBridgedAccessory Lightbulb Yellow LED
2017-06-24 00:20:40.588 <debug> mqtt subscribe Nodemcu/Control_Y_LED/status
2017-06-24 00:20:40.590 <info>  hap created 3 Accessories
2017-06-24 00:20:40.592 <info>  hap publishing bridge "MQTT Bridge" username=CC:22:3D:E3:CE:F6 port=51826 pincode=031-45-154
2017-06-24 00:20:40.736 <info>  hap Bridge listening on port 51826
2017-06-24 00:20:40.792 <info>  mqtt connected tcp://pi:password@127.0.0.1


third open terminal #2
run at terminal #2:
mosquitto_sub -d -h 127.0.0.1 -p 1883 -u pi -P password -t "Nodemcu/Control_R_LED/set"

Client mosqsub/1453-raspberryp sending CONNECT
Client mosqsub/1453-raspberryp received CONNACK
Client mosqsub/1453-raspberryp sending SUBSCRIBE (Mid: 1, Topic: Nodemcu/Control_R_LED/set, QoS: 0)
Client mosqsub/1453-raspberryp received SUBACK
Subscribed (mid: 1): 0

fourth open terminal #3
run at terminal #3:
mosquitto_pub -d -h 127.0.0.1 -p 1883 -u pi -P password -t "Nodemcu/Control_R_LED/set" -m "ON"

Client mosqpub/1314-raspberryp sending CONNECT
Client mosqpub/1314-raspberryp received CONNACK
Client mosqpub/1314-raspberryp sending PUBLISH (d0, q0, r0, m1, 'Nodemcu/Control_R_LED/set', ... (2 bytes))
Client mosqpub/1314-raspberryp sending DISCONNECT

terminal #1: no response

terminal #2:
Client mosqsub/1466-raspberryp received PUBLISH (d0, q0, r0, m0, 'Nodemcu/Control_R_LED/set', ... (2 bytes))
ON

but run at terminal #3:
mosquitto_pub -d -h 127.0.0.1 -p 51826 -u pi -P password -t "Nodemcu/Control_R_LED/set" -m "ON"

Client mosqpub/1316-raspberryp sending CONNECT
Error: The connection was lost.

Why Error: The connection was lost. ?
Why terminal #1: still no response ?

Thanks.

**Comment by hobbyquaker** [comment]
The Error in your last step is because you try to connect to the homekit-port with mosquitto_pub (`mosquitto_pub -d -h 127.0.0.1 -p 51826` is wrong). Correct usage is `mosquitto_pub -d -h 127.0.0.1 -p 1883`.
No Response in homekit2mqtt is because homekit2mqtt only subscribes to the topics you defined as statusOn, e.g. `"statusOn": "Nodemcu/Control_R_LED/status"`. When you do a publish like `mosquitto_pub -d -h 127.0.0.1 -p 1883 -u pi -P password -t "Nodemcu/Control_R_LED/status" -m "ON"` you should see something in homekit2mqtt's log. If you take your iOS device and use the Home app to Switch "Red LED" on and off you should see that homekit2mqtt publishes on the topic you configured as "setOn".

**Comment by shinyuan** [comment]
first run at terminal #1:

homekit2mqtt -u tcp://pi:password@127.0.0.1 \
    -m /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json \
    -v debug \
    --port 51826

*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2017-06-24 09:49:13.376 <info>  homekit2mqtt 0.6.9 starting
2017-06-24 09:49:13.394 <info>  mqtt trying to connect tcp://pi:password@127.0.0.1
2017-06-24 09:49:13.886 <info>  using hap-nodejs version 0.4.25
2017-06-24 09:49:13.933 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json
2017-06-24 09:49:13.938 <debug> loading accessories/Lightbulb.js
2017-06-24 09:49:13.946 <debug> addBridgedAccessory Lightbulb Red LED
2017-06-24 09:49:13.973 <debug> mqtt subscribe Nodemcu/Control_R_LED/status
2017-06-24 09:49:13.990 <debug> addBridgedAccessory Lightbulb Green LED
2017-06-24 09:49:13.996 <debug> mqtt subscribe Nodemcu/Control_G_LED/status
2017-06-24 09:49:14.002 <debug> addBridgedAccessory Lightbulb Yellow LED
2017-06-24 09:49:14.004 <debug> mqtt subscribe Nodemcu/Control_Y_LED/status
2017-06-24 09:49:14.006 <info>  hap created 3 Accessories
2017-06-24 09:49:14.008 <info>  hap publishing bridge "MQTT Bridge" username=CC:22:3D:E3:CE:F6 port=51826 pincode=031-45-154
2017-06-24 09:49:14.140 <info>  hap Bridge listening on port 51826
2017-06-24 09:49:14.198 <info>  mqtt connected tcp://pi:password@127.0.0.1

second open terminal #2
run at terminal #2:
mosquitto_pub -d -h 127.0.0.1 -p 1883 -u pi -P password -t "Nodemcu/Control_R_LED/status" -m "ON"
mosquitto_pub -d -h 127.0.0.1 -p 1883 -u pi -P password -t "Nodemcu/Control_R_LED/status" -m "OFF"

2017-06-24 09:49:28.682 <debug> < mqtt Nodemcu/Control_R_LED/status ON
2017-06-24 09:49:28.683 <debug> > hap set Red LED On true
2017-06-24 09:49:34.106 <debug> < mqtt Nodemcu/Control_R_LED/status OFF
2017-06-24 09:49:34.107 <debug> > hap set Red LED On false

Good enough, but why my iPhone/Home app can not find the homekit2mqtt bridge?

I change th other TF card that I make the HAP-NodeJS environment:
root@raspberrypi:/home/pi/HAP-NodeJS# node Core.js
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
HAP-NodeJS starting...
Parsing accessory: Fan_accessory.js
Parsing accessory: GarageDoorOpener_accessory.js
Parsing accessory: Light_accessory.js
Parsing accessory: Lock_accessory.js
Parsing accessory: MotionSensor_accessory.js
Parsing accessory: Outlet_accessory.js
Parsing accessory: TemperatureSensor_accessory.js
Parsing accessory: Thermostat_accessory.js
Parsing accessory: deskLamp_accessory.js

Why my iPhone/Home app can pair above accessory?

Really thanks for your help.

**Comment by shinyuan** [comment]
At link https://www.npmjs.com/package/homekit2mqtt
homekit2mqtt 
NPM version Dependency Status Build Status codecov XO code style License
...

Prerequisites:
Debian, Ubuntu, Raspbian or macOS
Node.js 6 or higher
If you're running on Linux, you'll need to make sure you have the libavahi-compat-libdnssd-dev package installed: sudo apt-get install libavahi-compat-libdnssd-dev

-->
Q1: mosquitto need to install before homekit2mqtt?
Q2: Without mosquitto, homekit2mqtt can work?

Really thanks for your help.

**Comment by hobbyquaker** [comment]
Could be that you can't pair your iOS device with homekit2mqtt because it's already been paired with HAP-NodeJs with the same Bridge name (`CC:22:3D:E3:CE:F6`). Try again with the following startup command:
```
homekit2mqtt -u tcp://pi:password@127.0.0.1 \
    -m /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json \
    -v debug \
    --port 51826 \
    --username CC:22:3D:E3:CE:F8
```

To your other Questions:
homekit2mqtt needs a MQTT Broker. This doesn't have to be neccessarily Mosquitto, it can be any MQTT Broker, but without a MQTT Broker homekit2mqtt does not make any sense. 
So as I always suggest to use Mosquitto as MQTT Broker I'm using Mosquitto as synonym for a MQTT Broker and would answer your questions with 
"yes - mosquitto needs to be installed" and "no - homekit2mqtt can't work without mosquitto".

**Comment by shinyuan** [comment]
terminal #1:
homekit2mqtt -u tcp://pi:password@192.168.0.180 \
    -m /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json \
    -v debug \
    --port 51826 \
    --username CC:22:3D:E3:CE:F7

--> 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
2017-06-25 01:13:30.962 <info>  homekit2mqtt 0.6.9 starting
2017-06-25 01:13:30.980 <info>  mqtt trying to connect tcp://pi:password@192.168.0.180
2017-06-25 01:13:31.443 <info>  using hap-nodejs version 0.4.25
2017-06-25 01:13:31.488 <info>  loading HomeKit to MQTT mapping file /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json
2017-06-25 01:13:31.492 <debug> loading accessories/Lightbulb.js
2017-06-25 01:13:31.501 <debug> addBridgedAccessory Lightbulb Red LED
2017-06-25 01:13:31.526 <debug> mqtt subscribe Nodemcu/Control_R_LED/status
2017-06-25 01:13:31.542 <debug> addBridgedAccessory Lightbulb Green LED
2017-06-25 01:13:31.548 <debug> mqtt subscribe Nodemcu/Control_G_LED/status
2017-06-25 01:13:31.553 <debug> addBridgedAccessory Lightbulb Yellow LED
2017-06-25 01:13:31.555 <debug> mqtt subscribe Nodemcu/Control_Y_LED/status
2017-06-25 01:13:31.557 <info>  hap created 3 Accessories
2017-06-25 01:13:31.559 <info>  hap publishing bridge "MQTT Bridge" username=CC:22:3D:E3:CE:F8 port=51826 pincode=031-45-154
2017-06-25 01:13:31.687 <info>  hap Bridge listening on port 51826
2017-06-25 01:13:31.739 <info>  mqtt connected tcp://pi:password@192.168.0.180

After my iPhone/Home app can pair
terminal #1:
-->
2017-06-25 01:17:45.759 <info>  hap paired 9B65938C-07F6-44A4-8929-07B2795FB0D6
2017-06-25 01:17:49.038 <info>  < hap bridge identify (paired)
2017-06-25 01:17:50.849 <debug> < hap get Green LED On
2017-06-25 01:17:50.850 <debug> > hap re_get Green LED On true
2017-06-25 01:17:51.342 <debug> < hap identify Green LED (paired)
2017-06-25 01:18:02.562 <debug> < hap get Green LED On
2017-06-25 01:18:02.563 <debug> > hap re_get Green LED On true
2017-06-25 01:18:02.821 <debug> < hap get Red LED On
2017-06-25 01:18:02.821 <debug> > hap re_get Red LED On true
2017-06-25 01:18:03.305 <debug> < hap identify Red LED (paired)
2017-06-25 01:18:13.769 <debug> < hap get Red LED On
2017-06-25 01:18:13.770 <debug> > hap re_get Red LED On true
2017-06-25 01:18:14.039 <debug> < hap get Yellow LED On
2017-06-25 01:18:14.040 <debug> > hap re_get Yellow LED On true
2017-06-25 01:18:14.520 <debug> < hap identify Yellow LED (paired)
2017-06-25 01:18:25.253 <debug> < hap get Yellow LED On
2017-06-25 01:18:25.254 <debug> > hap re_get Yellow LED On true
2017-06-25 01:18:25.280 <debug> < hap get Red LED On
2017-06-25 01:18:25.281 <debug> > hap re_get Red LED On true
2017-06-25 01:18:25.282 <debug> < hap get Yellow LED On
2017-06-25 01:18:25.283 <debug> > hap re_get Yellow LED On true
2017-06-25 01:18:25.284 <debug> < hap get Green LED On
2017-06-25 01:18:25.285 <debug> > hap re_get Green LED On true

terminal #2:
mosquitto_sub -d -h 192.168.0.180 -p 1883 -u pi -P password -t "Nodemcu/Control_R_LED/status"

After my iPhone/Home app press "Red LED"
terminal #1:
-->
2017-06-25 01:20:32.781 <debug> < hap set Red LED On 0
2017-06-25 01:20:32.782 <debug> > mqtt Nodemcu/Control_R_LED/set OFF

terminal #2:
-->
Client mosqsub/1351-raspberryp sending CONNECT
Client mosqsub/1351-raspberryp received CONNACK
Client mosqsub/1351-raspberryp sending SUBSCRIBE (Mid: 1, Topic: Nodemcu/Control_R_LED/set, QoS: 0)
Client mosqsub/1351-raspberryp received SUBACK
Subscribed (mid: 1): 0
Client mosqsub/1351-raspberryp sending PINGREQ
Client mosqsub/1351-raspberryp received PINGRESP
Client mosqsub/1351-raspberryp received PUBLISH (d0, q0, r0, m0, 'Nodemcu/Control_R_LED/set', ... (3 bytes))
OFF


My Arduino code: MQTT_NodeMCU_LEDs.ino
#define MQTT_Server "192.168.0.180"
#define MQTT_Port 1883
#define MQTT_User "pi"
#define MQTT_Password "password"

// MQTT subscribe/publish Topic
#define MQTT_R_LED_set_TOPIC "Nodemcu/Control_R_LED/set"
#define MQTT_G_LED_set_TOPIC "Nodemcu/Control_G_LED/set"
#define MQTT_Y_LED_set_TOPIC "Nodemcu/Control_Y_LED/set"

Arduino IDE/Serial Monitor:
-->
MQTT_Callback:
Nodemcu/Control_R_LED/set
OFF
Red LED: OFF

Work almost perfect,
  even 3 LEDs connect to NodeMCU can control by Home app/Siri.

But I don't why iOS device already been paired with HAP-NodeJs with the same Bridge name
  then must change username (CC:22:3D:E3:CE:F6) to new one and repair Bridge (and all it's accessories),
  even if I press key Ctrl+C or system halt?

HAP-NodeJs (node Core.js) without this problem.

Really thanks for your help.

**Comment by hobbyquaker** [comment]
Not sure if I understand right... 

Normally you shouldn't need to change the username or repair after a pairing was successful. Homekit2mqtt saves some data regarding the pairing, there is also an command line option to choose where to save this (`--storagedir`). As long as the username is unchanged and homekit2mqtt can load the persisted data everything should be ok.

To run homekit2mqtt in background and autostart it on system boot I suggest to use [pm2](https://github.com/Unitech/pm2), a node.js based process manager that's quite comfortable.

**Comment by shinyuan** [comment]
Hi awesome maker (Sebastian Raff),

I will try homekit2mqtt [option]
  -s, --storagedir  directory to store homekit data
later.

The easy way to autostart it on system boot, can do as below too 

sudo vi /etc/rc.local

_IP=$(hostname -I) || true
if [ "$_IP" ]; then
  printf "My IP address is %s\n" "$_IP"
fi

#cd /home/pi/HAP-NodeJS
#node Core.js

homekit2mqtt -u tcp://pi:password@192.168.0.160 \
    -m /usr/lib/node_modules/homekit2mqtt/homekit2mqtt.json \
    -v debug \
    --port 51826 \
    --username CC:22:3D:E3:CE:FB

exit 0

You can Close issue.
Really thanks for your help.
