### ISSUE TITLE
Speaker accessory does not seem to work

### ISSUE THREAD

**Issue by tardisx** [hobbyquaker/homekit2mqtt#35]
I cannot seem to get the Speaker accessory to work. I do note it is not in the example file.

The parameters passed to mqttPub seem different to a working one (Thermostat) in createAccessory. But I know nothing about node so that's just a guess :-)

```
2017-08-09 18:21:09.140 <info>  homekit2mqtt 0.6.11 starting
2017-08-09 18:21:09.142 <info>  mqtt trying to connect mqtt://127.0.0.1
2017-08-09 18:21:09.166 <info>  using hap-nodejs version 0.4.27
2017-08-09 18:21:09.169 <info>  loading HomeKit to MQTT mapping file /home/justin/gurrs-homekit2mqtt.json
/usr/lib/node_modules/homekit2mqtt/node_modules/mqtt/lib/client.js:416
  var resubscribe = obj.resubscribe
                       ^

TypeError: Cannot read property 'resubscribe' of undefined
    at MqttClient.subscribe (/usr/lib/node_modules/homekit2mqtt/node_modules/mqtt/lib/client.js:416:24)
    at mqttSub (/usr/lib/node_modules/homekit2mqtt/index.js:93:18)
    at Object.createAccessory_Speaker [as Speaker] (/usr/lib/node_modules/homekit2mqtt/accessories/Speaker.js:20:9)
    at Object.keys.forEach.id (/usr/lib/node_modules/homekit2mqtt/index.js:189:58)
    at Array.forEach (native)
    at Object.<anonymous> (/usr/lib/node_modules/homekit2mqtt/index.js:182:22)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
```

```
 {
  "Speaker": {
    "service": "Speaker",
    "name": "Speaker",
    "topic": {
      "setMute": "home/speaker/mute"
    },
    "payload": {
      "muteTrue": "mute",
      "muteFalse": "unmute"
    }
  }
}
```

Cheers

**Comment by hobbyquaker** [comment]
should be fixed in v0.6.12
