### ISSUE TITLE
SyntaxError: Block-scoped declarations

### ISSUE THREAD

**Issue by philgin** [hobbyquaker/homekit2mqtt#45]
Note: Fisrt time using homekit2mqtt. (Currently using homebridge and mosquitto, they don't conflict right?)
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Raspbian
Description:	Raspbian GNU/Linux 8.0 (jessie)
Release:	8.0
Codename:	jessie

$ nodejs -v
v7.10.1
$ node -v
v4.3.2
$ npm -v
5.3.0

$ sudo homekit2mqtt -v debug
/usr/local/lib/node_modules/homekit2mqtt/index.js:24
let mqttConnected;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:134:18)
    at node.js:962:3
```

**Comment by philgin** [comment]
same result with 
$ node -v
v8.9.1

**Comment by philgin** [comment]
Nevermind. It worked when I ran it with root
```
sudo homekit2mqtt -v debug
```
Thanks for your great work!!!
